title: neat plugins plus
theme_config:
  show_description: true
description: >-
  All the dalamud plugins that can be found on github. This is automatically updated every hour and not vetted in the least.
baseurl: /neat-plugins-plus
url: https://kalilistic.github.io/neat-plugins-plus

# Build settings
remote_theme: riggraz/no-style-please
plugins:
  - jekyll-feed