name: Update Data

on:
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run update
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        python main.py
    - name: Add and commit update
    - uses: EndBug/add-and-commit@v7
      with:
        author_name: GitHub Action
        author_email: github-actions[bot]@users.noreply.github.com
        message: Update plugins
